// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { Node } from "./Node";

export type Commit = { _id: Id<Commit>, oid: string, root: Id<Node>, parents: Array<Id<Commit>>, };