// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullNode } from "./FullNode";
import type { NodeInfo } from "./NodeInfo";

export type EitherNode = { "Full": FullNode } | { "Short": NodeInfo } | { "NotFound": string };