// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "./ContentKind";
import type { FileContent } from "./FileContent";
import type { Id } from "./Id";
import type { Node } from "./Node";

export type FullNode = { content: FileContent, text: Array<string> | null, _id: Id<Node>, kind: ContentKind, };