// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileContent } from "./FileContent";
import type { Id } from "./Id";

export type Node = { _id: Id<Node>, oid: string, content: FileContent, };