// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "./ContentKind";
import type { Id } from "./Id";
import type { Node } from "./Node";

export type NodeInfo = { _id: Id<Node>, kind: ContentKind, };