// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { Line } from "./Line";

export type Range = { _id: Id<Range>, line_id: Id<Line>, start: number, end: number, };