services:
  backend:
    build:
      context: ./backend/
      target: shatterbird-server
    command: ["--db-url", "mongodb://mongo:27017/db", "--addr", "0.0.0.0:3000"]
    networks:
      - back
      - front
    environment:
      - RUST_LOG=info
  mongo:
    image: mongo:7-jammy
    volumes:
      - mongo-data:/data/db
    networks:
      - back
  frontend:
    build:
      context: ./frontend/
    environment:
      - CADDY_DOMAIN=*
      - BACKEND_HOST=backend:3000
    volumes:
      - caddy-data:/data
    ports:
      - 80:80
      - 443:443
    networks:
      - front

  indexer:
    build:
      context: ./backend/
      target: shatterbird-indexer
    profiles:
      - build
  cli:
    build:
      context: ./backend/
      target: shatterbird-cli
    profiles:
      - build
volumes:
  mongo-data: {}
  caddy-data: {}
networks:
  back: {}
  front: {}
