// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * Содержимое файла, который не удалось разделить на отдельные строки
 */
export type BlobFile = { 
/**
 * Идентификатор объекта в базе данных
 */
_id: Id<BlobFile>, 
/**
 * Содержимое файла
 */
data: Array<number>, };