// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobFile } from "./BlobFile";
import type { Id } from "./Id";
import type { Line } from "./Line";
import type { Node } from "./Node";

export type FileContent = { "Symlink": { 
/**
 * Путь, на который ссылается эта ссылка
 */
target: string, } } | { "Directory": { 
/**
 * Объекты. входящие в эту директорию и их имена
 */
children: { [key: string]: Id<Node> }, } } | { "Text": { 
/**
 * Суммарный размер файла
 */
size: bigint, 
/**
 * Список строк, входящих в этот файл
 */
lines: Array<Id<Line>>, } } | { "Blob": { 
/**
 * Суммарный размер файла
 */
size: bigint, 
/**
 * Идентификатор объекта, содержащего этот файл
 */
content: Id<BlobFile>, } };