// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BlobFile} from "./BlobFile";
import type {Id} from "./Id";
import type {Line} from "./Line";
import type {Node} from "./Node";

/**
 * Хранит полную информацию об узле файлового дерева
 */
export type FullNode = {
    /**
     * Идентифкатор этого узла в базе данных
     */
    _id: Id<Node>,

    /**
     * Тип узла
     */
    kind: "Symlink" | "Directory" | "Text" | "Blob",

    content: {
        "Symlink": {
            /**
             * Ссылка на целевой файл
             */
            target: string,
        }
    } | {
        "Directory": {
            /**
             * Дочерние узлы этой директории вместе с их именами
             */
            children: {
                [key: string]: {
                    /**
                     * Идентифкатор этого узла в базе данных
                     */
                    _id: Id<Node>,
                    /**
                     * Тип узла
                     */
                    kind: "Symlink" | "Directory" | "Text" | "Blob",
                }
            },
        }
    } | {
        "Text": {
            /**
             * Размер в байтах
             */
            size: bigint,
            /**
             * Строки файла
             */
            lines: Array<{
                /**
                 * Идентификатор объекта в базе данных
                 */
                _id: Id<Line>,
                /**
                 * Текст строки
                 */
                text: string,
            }>,
        }
    } | {
        "Blob": {
            /**
             * Размер в байтах
             */
            size: bigint,
            /**
             * Идентификатор этого файла в базе данных
             */
            content: Id<BlobFile>,
        }
    },
};