// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * Содержимое отдельной строки текстового файла
 */
export type Line = { 
/**
 * Идентификатор объекта в базе данных
 */
_id: Id<Line>, 
/**
 * Текст строки
 */
text: string, };