// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobFile } from "./BlobFile";
import type { Id } from "./Id";
import type { Line } from "./Line";

/**
 * Объект в файловом дереве
 */
export type Node = { 
/**
 * Идентификатор объекта в базе данных
 */
_id: Id<Node>, 
/**
 * Хранит хэш, который используется для идентификации соответствующего объекта в Git
 */
oid: string, 
/**
 * Содержимое объекта, в зависимости от его типа
 */
content: { "Symlink": { 
/**
 * Путь, на который ссылается эта ссылка
 */
target: string, } } | { "Directory": { 
/**
 * Объекты. входящие в эту директорию и их имена
 */
children: { [key: string]: Id<Node> }, } } | { "Text": { 
/**
 * Суммарный размер файла
 */
size: bigint, 
/**
 * Список строк, входящих в этот файл
 */
lines: Array<Id<Line>>, } } | { "Blob": { 
/**
 * Суммарный размер файла
 */
size: bigint, 
/**
 * Идентификатор объекта, содержащего этот файл
 */
content: Id<BlobFile>, } }, };