// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { Line } from "./Line";

/**
 * Описание подстроки в файле
 */
export type Range = { 
/**
 * Идентификатор объекта в базе данных
 */
_id: Id<Range>, 
/**
 * Идентификатор строки, в которой находится подстрока
 */
line_id: Id<Line>, 
/**
 * Полный путь к этому файлу
 */
path: Array<Id<Line>>, 
/**
 * Индекс первого символа подстроки
 */
start: number, 
/**
 * Индекс конца подстроки
 */
end: number, };