// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * Узел графа
 */
export type Vertex = { 
/**
 * Идентификатор объекта в базе данных
 */
_id: Id<Vertex>, 
/**
 * Информация об узле, предоставленная LSIF
 */
data: { 
/**
 * Вид узла
 */
vertex: "MetaData" | "Project" | "Document" | "Range" | "ResultSet" | "Moniker" | "PackageInformation" | "DefinitionResult" | "DeclarationResult" | "TypeDefinitionResult" | "ReferenceResult" | "ImplementationResult" | "FoldingRangeResult" | "HoverResult" | "DocumentSymbolResult" | "DocumentLinkResult" | "DiagnosticResult", }, };